apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bvgr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bvgr
    app.kubernetes.io/part-of: tkrw-pr714-0075-0066-app
  name: devfile-sample-bvgr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bvgr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bvgr
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0066-tenant/tkrw-pr714-0075-0066-app/devfile-sample-bvgr@sha256:0da97677c019cc451589354afbb4d8a1d97291e4009bb51725acb2f93f31d443
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
